---
- name: Securing MariaDB
  hosts: db_servers
  become: yes

  tasks:
    - name: Assign password to MariaDB root user
      mysql_user:
        login_unix_socket: /var/lib/mysql/mysql.sock
        name: root
        host_all: yes
        login_user: root
        login_password: "{{ pw }}"
        update_password: always
        password: "{{ pw }}"

    - name: Authentication credentials copied to root home directory
      copy:
        src: files/my.cnf
        dest: /etc/my.cnf

    - name: Remove anonymous user accounts
      mysql_user:
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_user: root
        login_password: "{{ pw }}"
        name: ''
        host_all: yes
        state: absent

    - name: Remove test database
      mysql_db:
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_user: root
        login_password: "{{ pw }}"
        name: test
        state: absent
