---
- name: Ensure the web content is reverted to its original version
  hosts: web_servers
  gather_facts: false
  become: true

  tasks:
    - name: the original web content is deployed
      copy:
        content: "This is {{ inventory_hostname }}\n"
        dest: /var/www/html/index.html
      notify: Varnish Cache is clean

  handlers:
    - name: Varnish Cache is clean
      service:
        name: varnish
        state: restarted
