---
- name: Ensure new web content is deployed
  hosts: web_servers
  gather_facts: false
  become: true
  serial: 1

  tasks:
    - name: the web server is removed from service during the update
      haproxy:
        socket: /var/lib/haproxy/stats
        state: disabled
        backend: web-farm
        host: "{{ inventory_hostname }}"
      delegate_to: rh1

    - name: update html file
      copy:
        content: |
          host {{ inventory_hostname }} v3
        dest: "{{ www_path }}"
      notify: Varnish Cache is clean

    - name: pause
      pause:
        seconds: 5
##    - name: the new content is deployed
#      synchronize:
#        src: "new_web_content/{{ inventory_hostname }}/"
#        dest: "{{ www_path }}"
#        delete: true
#      notify: Varnish Cache is clean

  post_tasks:
    - name: Smoke Test - Ensure HTTP 200 OK
      uri:
        url: "http://localhost"
        status_code: 200

    # If the test fails, servers are not re-enabled
    # in the load balancers, and the update process halts.
    - name: the healthy web server is enabled in HAProxy
      haproxy:
        socket: /var/lib/haproxy/stats
        state: enabled
        backend: web-farm
        host: "{{ inventory_hostname }}"
      delegate_to: rh1

  handlers:
    - name: Varnish Cache is clean
      service:
        name: varnish
        state: restarted
