---
- name: Ensure HAProxy is deployed
  hosts: rh3
  gather_facts: false
  become: true

  tasks:
    - name: the haproxy package is installed
      yum:
        name: haproxy
        state: present

    - name: the /etc/pki/haproxy directory exists
      file:
        path: /etc/pki/haproxy
        state: directory
        owner: root
        mode: '700'

    - name: the SSL file for HTTPS termination is deployed
      assemble:
        # You need to create that file from the
        # servera.lab.example.com.{crt,key} files under the
        # files/ directory
        src: files
        remote_src: false
        regexp: "^servera\\.lab\\.example\\.com\\.(crt|key)$"
        dest: /etc/pki/haproxy/haproxy.pem

    - name: the HAProxy configuration file is deployed
      copy:
        # You need to complete that configuration file
        src: files/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg


    - name: check haproxy
      command: 
        cmd: haproxy -c -f /etc/haproxy/haproxy.cfg
      register: test_haproxy

    - name: the haproxy service is started and enabled
      service:
        name: haproxy
        state: started
        enabled: yes

    - name: the http and https firewall services are opened
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      loop:
        - http
        - https

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
