---
- name: Access an NFS share
  hosts: servera.lab.example.com
  become: true
  vars:
    shared_dir: /srv/operators
    mount_point: /operators_data

  tasks:
    - name: the package for NFS client is installed
      yum:
        name: nfs-utils
        state: present

    - name: the NFS share is mounted and in /etc/fstab
      mount:
        path: "{{ mount_point }}"
        src: serverc.lab.example.com:{{ shared_dir }}
        state: mounted
        fstype: nfs
